## Tarea S12.01. APIS REST

### *Andrey Ismagilov*
### *Fecha 12/02/2026*

In [6]:
import pandas as pd
import requests
from requests.exceptions import HTTPError

In [7]:
r = requests.get('https://httpbin.org/basic-auth/user/pass', auth=('user', 'pass'))
r.status_code

200

### **Nivel 1**

### **Ejercicio 1.** 
###  Consulta la API pública JSONPlaceholder utilizando el método GET para obtener:

In [8]:
url = 'https://jsonplaceholder.typicode.com/'

# Comprobamos que existe la pagina web de "url"
try:
    r = requests.get(url)
    r.raise_for_status()
except HTTPError as http_err:
    print(f"HTTP error se ha producido: {http_err}")
except Exception as err:
    print(f"Se ha producido otro error: {err}")
else:
    print("Exito.")

Exito.

- ##### Lista de publicaciones (/posts)

In [9]:
url_posts = 'https://jsonplaceholder.typicode.com/posts'
r_posts = requests.get(url_posts)
lista_posts = r_posts.json()
lista_posts[:3]

[{'userId': 1,
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}]

- ##### Lista de usuarios (/users)

In [10]:
url_users = 'https://jsonplaceholder.typicode.com/users'
r_users = requests.get(url_users)
lista_users = r_users.json()
lista_users[:3]

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}}]

- ##### Lista de tareas (/todos)

In [11]:
url_todos = 'https://jsonplaceholder.typicode.com/todos'
r_todos = requests.get(url_todos)
lista_todos = r_todos.json()
lista_todos[:3]

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False},
 {'userId': 1,
  'id': 2,
  'title': 'quis ut nam facilis et officia qui',
  'completed': False},
 {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False}]

### **Ejercicio 2.** 
###  Muestra por pantalla:
### - La cantidad total de cada recurso.
### - El código de estado de cada petición.

In [12]:
print(f'Recurso POSTS: {url_posts}')
print(f'Cantitad: {len(lista_posts)}')
print(f'Códico de estado: {r_posts.status_code}')


print(f'Recurso USERS: {url_users}')
print(f'Cantitad: {len(lista_users)}')
print(f'Códico de estado: {r_users.status_code}')

print(f'Recurso TODOS: {url_todos}')
print(f'Cantitad: {len(lista_todos)}')
print(f'Códico de estado: {r_todos.status_code}')

Recurso POSTS: https://jsonplaceholder.typicode.com/posts
Cantitad: 100
Códico de estado: 200
Recurso USERS: https://jsonplaceholder.typicode.com/users
Cantitad: 10
Códico de estado: 200
Recurso TODOS: https://jsonplaceholder.typicode.com/todos
Cantitad: 200
Códico de estado: 200

### **Ejercicio 3.** 
###  Realiza una petición a una publicación inexistente para obtener un error 404 y muestra el código de estado recibido.

In [13]:
url_not_exists = url + '/not_exist'

r_not_exist = requests.get(url_not_exists)
print(f'Recurso NOT_exist: {url_not_exists}')
print(f'Códico de estado: {r_not_exist.status_code}')

Recurso NOT_exist: https://jsonplaceholder.typicode.com//not_exist
Códico de estado: 404

### **Ejercicio 4.**  
### Realiza una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.

##### Obtenemos el número de publicaciones del recurso POSTS

In [14]:
r_posts = requests.get(url_posts)
lista_posts = r_posts.json()
num_de_public = len(lista_posts)

##### Creamos  la nueva publicación ficticia

In [15]:
public_ficticia = {
    'userId': 1,
    'id': num_de_public + 1,
    'title': 'title fictitious AI',
    'body': 'message fictitious AI'
    }

r_de_post = requests.post(url_posts, data = public_ficticia)

if r_de_post.status_code == 201:
    print('Exito.')
    print(f'Codico de estado: {r_de_post.status_code}')
    print('Cuerpo de publicación: \n', r_de_post.request.body)
else:
    print(f'Error. Codico de error: {r_de_post.status_code}')

Exito.
Codico de estado: 201
Cuerpo de publicación:
 userId=1&id=101&title=title+fictitious+AI&body=message+fictitious+AI

### **Ejercicio 5.**  
###  Realiza una petición PATCH para modificar parcialmente una publicación existente.

In [16]:
id_post_a_modificar = 1

url_a_modificar = url_posts + '/' + str(id_post_a_modificar)

public_ficticia_modificada = {
    "body": "Modificada por PATCH"
  }

r_de_patch = requests.patch(url_a_modificar, data = public_ficticia_modificada)

if r_de_patch.status_code == 200:
  print('Modificado.')
  print(f'Codico de estado: {r_de_patch.status_code}')
else:
  print(f'Error. Codico de error: {r_de_patch.status_code}')

Modificado.
Codico de estado: 200

### **Ejercicio 6.**  
###  Haz una petición DELETE sobre una publicación.

In [17]:
id_post_a_eliminar = 2

url_a_eliminar = url_posts + '/' + str(id_post_a_eliminar)

r_de_eliminar = requests.delete(url_a_eliminar)

if r_de_eliminar.status_code == 200:
  print('Modificado.')
  print(f'Codico de estado: {r_de_eliminar.status_code}')
else:
  print(f'Error. Codico de error: {r_de_eliminar.status_code}')

Modificado.
Codico de estado: 200

### **Nivel 2**

### **Ejercicio 1.** 
###  Explora el repositorio de Public APIs y elige una API que permita realizar peticiones GET.

He eligido API **Aviationstack** que proporciona acceso a los datos globales de aviación y estado de vuelos en tiempo real.

### **Ejercicio 2.**

- ##### Revisa la sección de endpoints disponibles. En un markdown, apunta al menos dos endpoints diferentes.

API **Aviationstack** cuenta 11 endpoints incluido los datos de vuelos, rutas, aeropuertos, aerolínias, horarios de vuelos etc.

- #### Comprueba si ofrece filtros o parámetros opcionales interesantes. En un markdown, anótalos.

El API permite filtrar los datos por varias parámetros. 

Por ejemplo en el endpoint FLIGHT se puede pasar un codico de aerolinia, un nombre de aerolinia, una fecha de vuelos buscados, un número de vuelo, estado de vuelo y mucho más.

Hay un parametro interesante llamado **callback** que permite pasar la respuesta de peticion en formato JSON a una función predefinida

Ademas el parametro **lang** permite traducir los nombres de aeropuertos, ciudades y países a muchas idiomas.

Algunos endpoints de **Aviationstack** proporcionan tambien las funciones de autocompletar de aplicación de usuario. Para obtener sugerencias de autocompletar se agrega el parámetro **search** a la URL de petición de la API y le asigna a un término de busqueda.

### **Ejercicio 3.**

#### Haz una petición GET sencilla.

- #### Muestra el código de estado de la respuesta.

In [19]:
access_key = '22c8207d1c76c955d2f67e558ebf42bd'

endpoint_flights = 'https://api.aviationstack.com/v1/flights'

querystring = {
    'access_key': access_key,
    'airline_iata': 'VY' # `por ejemplo Vueling
    }

headers = {"Accept": "application/json"}

r_vuelos = requests.get(url, headers=headers, params=querystring)

if r_vuelos.status_code == 200:
    print('Éxito.')
    print(f'Codico de estado: {r_vuelos.status_code}')
else:
    print(f'Error. Codico de error: {r_vuelos.status_code}')

Éxito.
Codico de estado: 200

- #### Imprime de forma clara algunos de los campos de la respuesta JSON.

In [ ]:
r_vuelos.json().keys()

dict_keys(['pagination', 'data'])

In [ ]:
r_vuelos.json()['data'][0].keys()

dict_keys(['flight_date', 'flight_status', 'departure', 'arrival', 'airline', 'flight', 'aircraft', 'live'])

### **Ejercicio 4.**

 #### Convierte los datos a un DataFrame de pandas y muestra las primeras filas de DataFrame.

In [ ]:
df_vuelos = pd.DataFrame(r_vuelos.json()['data'])

Vemos que valores de las columnas **departure, arrival, arrival, flight, aircraft** estan en formato JSON.

In [ ]:
df_vuelos.head(3)

,flight_date,flight_status,departure,arrival,airline,flight,aircraft,live
0,2026-02-16,scheduled,"{'airport': 'El Prat De Llobregat', 'timezone'...","{'airport': 'Ezeiza Ministro Pistarini', 'time...","{'name': 'Vueling', 'iata': 'VY', 'icao': 'VLG'}","{'number': '9781', 'iata': 'VY9781', 'icao': '...",None,None
1,2026-02-15,active,"{'airport': 'Heathrow', 'timezone': 'Europe/Lo...","{'airport': 'Barajas', 'timezone': 'Europe/Mad...","{'name': 'Vueling', 'iata': 'VY', 'icao': 'VLG'}","{'number': '5227', 'iata': 'VY5227', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None
2,2026-02-15,active,"{'airport': 'Barajas', 'timezone': 'Europe/Mad...","{'airport': 'Agoncillo', 'timezone': 'Europe/M...","{'name': 'Vueling', 'iata': 'VY', 'icao': 'VLG'}","{'number': '5622', 'iata': 'VY5622', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None

Todas las columnas Python ha tipificado como object.

In [ ]:
df_vuelos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   flight_date    100 non-null    object
 1   flight_status  99 non-null     object
 2   departure      100 non-null    object
 3   arrival        100 non-null    object
 4   airline        100 non-null    object
 5   flight         100 non-null    object
 6   aircraft       96 non-null     object
 7   live           0 non-null      object
dtypes: object(8)
memory usage: 6.4+ KB

Vemos que casi no hay valores nulos, exepto la columa **live**.

In [ ]:
null_counts = df_vuelos.isnull().sum()

null_porcentaje = (null_counts / len(df_vuelos)) * 100

null_info = pd.DataFrame({
    'columna': null_counts.index,
    'nulos': null_counts.values,
    'Porcenraje de nulos': null_porcentaje
})

null_info

                     columna  nulos  Porcenraje de nulos
flight_date      flight_date      0                  0.0
flight_status  flight_status      1                  1.0
departure          departure      0                  0.0
arrival              arrival      0                  0.0
airline              airline      0                  0.0
flight                flight      0                  0.0
aircraft            aircraft      4                  4.0
live                    live    100                100.0

Aplicamos el metodo json_normalize a dataframes **df_salidas, df_llegadas, df_aerolinias, df_flights y df_aeronaves** para convertir las claves de objeto JSON a las columnas.

In [ ]:
df_salidas = pd.json_normalize(df_vuelos.departure).add_prefix('departure_')
df_salidas.head(3)

,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,departure_estimated,departure_actual,departure_estimated_runway,departure_actual_runway
0,El Prat De Llobregat,Europe/Madrid,BCN,LEBL,1,None,NaN,2026-02-16T01:30:00+00:00,2026-02-16T01:30:00+00:00,None,None,None
1,Heathrow,Europe/London,LHR,EGLL,5,C62,NaN,2026-02-15T18:45:00+00:00,2026-02-15T18:45:00+00:00,None,None,None
2,Barajas,Europe/Madrid,MAD,LEMD,4,None,NaN,2026-02-15T20:00:00+00:00,2026-02-15T20:00:00+00:00,None,None,None

In [ ]:
df_llegadas = pd.json_normalize(df_vuelos.arrival).add_prefix('arrival_')
df_llegadas.head(3)

,arrival_airport,arrival_timezone,arrival_iata,arrival_icao,arrival_terminal,arrival_gate,arrival_baggage,arrival_scheduled,arrival_delay,arrival_estimated,arrival_actual,arrival_estimated_runway,arrival_actual_runway
0,Ezeiza Ministro Pistarini,America/Argentina/Buenos_Aires,EZE,SAEZ,IA,None,None,2026-02-16T11:10:00+00:00,NaN,None,None,None,None
1,Barajas,Europe/Madrid,MAD,LEMD,4S,None,None,2026-02-15T22:10:00+00:00,63.0,None,None,None,None
2,Agoncillo,Europe/Madrid,RJL,LERJ,None,None,None,2026-02-15T21:15:00+00:00,33.0,None,None,None,None

In [ ]:
df_aerolinias = pd.json_normalize(df_vuelos.airline).add_prefix('airline_')
df_aerolinias.head(3)

  airline_name airline_iata airline_icao
0      Vueling           VY          VLG
1      Vueling           VY          VLG
2      Vueling           VY          VLG

In [ ]:
df_flights = pd.json_normalize(df_vuelos.flight).add_prefix('flight_')
df_flights.head(3)

,flight_number,flight_iata,flight_icao,flight_codeshared.airline_name,flight_codeshared.airline_iata,flight_codeshared.airline_icao,flight_codeshared.flight_number,flight_codeshared.flight_iata,flight_codeshared.flight_icao,flight_codeshared
0,9781,VY9781,VLG9781,iberia,ib,ibe,2601,ib2601,ibe2601,NaN
1,5227,VY5227,VLG5227,iberia,ib,ibe,722,ib722,ibe722,NaN
2,5622,VY5622,VLG5622,iberia,ib,ibe,2222,ib2222,ibe2222,NaN

In [ ]:
df_aeronaves = pd.json_normalize(df_vuelos['aircraft']).add_prefix('aircraft')
df_aeronaves.head(3)

   aircraftregistration  aircraftiata  aircrafticao aircrafticao24
0                   NaN           NaN           NaN            NaN
1                   NaN           NaN           NaN         346057
2                   NaN           NaN           NaN         344307

Unimos los datafames creados al unico.

In [ ]:
df_vuelos_total = pd.concat([df_salidas, df_llegadas, df_aerolinias, df_flights, df_aeronaves], axis=1)
df_vuelos_total.head(5)

,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,departure_estimated,departure_actual,...,flight_codeshared.airline_iata,flight_codeshared.airline_icao,flight_codeshared.flight_number,flight_codeshared.flight_iata,flight_codeshared.flight_icao,flight_codeshared,aircraftregistration,aircraftiata,aircrafticao,aircrafticao24
0,El Prat De Llobregat,Europe/Madrid,BCN,LEBL,1,None,NaN,2026-02-16T01:30:00+00:00,2026-02-16T01:30:00+00:00,None,...,ib,ibe,2601,ib2601,ibe2601,NaN,NaN,NaN,NaN,NaN
1,Heathrow,Europe/London,LHR,EGLL,5,C62,NaN,2026-02-15T18:45:00+00:00,2026-02-15T18:45:00+00:00,None,...,ib,ibe,722,ib722,ibe722,NaN,NaN,NaN,NaN,346057
2,Barajas,Europe/Madrid,MAD,LEMD,4,None,NaN,2026-02-15T20:00:00+00:00,2026-02-15T20:00:00+00:00,None,...,ib,ibe,2222,ib2222,ibe2222,NaN,NaN,NaN,NaN,344307
3,Barajas,Europe/Madrid,MAD,LEMD,4,None,NaN,2026-02-15T20:00:00+00:00,2026-02-15T20:00:00+00:00,2026-02-15T20:16:00+00:00,...,ib,ibe,425,ib425,ibe425,NaN,NaN,NaN,NaN,344648
4,Barajas,Europe/Madrid,MAD,LEMD,4,None,NaN,2026-02-15T19:50:00+00:00,2026-02-15T19:50:00+00:00,2026-02-15T20:07:00+00:00,...,ib,ibe,1331,ib1331,ibe1331,NaN,NaN,NaN,NaN,34604B

In [ ]:
print(df_vuelos_total.columns)

Index(['departure_airport', 'departure_timezone', 'departure_iata',
       'departure_icao', 'departure_terminal', 'departure_gate',
       'departure_delay', 'departure_scheduled', 'departure_estimated',
       'departure_actual', 'departure_estimated_runway',
       'departure_actual_runway', 'arrival_airport', 'arrival_timezone',
       'arrival_iata', 'arrival_icao', 'arrival_terminal', 'arrival_gate',
       'arrival_baggage', 'arrival_scheduled', 'arrival_delay',
       'arrival_estimated', 'arrival_actual', 'arrival_estimated_runway',
       'arrival_actual_runway', 'airline_name', 'airline_iata', 'airline_icao',
       'flight_number', 'flight_iata', 'flight_icao',
       'flight_codeshared.airline_name', 'flight_codeshared.airline_iata',
       'flight_codeshared.airline_icao', 'flight_codeshared.flight_number',
       'flight_codeshared.flight_iata', 'flight_codeshared.flight_icao',
       'flight_codeshared', 'aircraftregistration', 'aircraftiata',
       'aircrafticao', 'aircrafticao24'],
      dtype='object')

### **Nivel 3**

### **Ejercicio 1.**

#### Utiliza la API de Open Data BCN para Buscar un dataset de tu interés mediante package_search y package_show.

Miramos la lista dels datasets usando **package_search**.

In [78]:
url_bcn = 'https://opendata-ajuntament.barcelona.cat/data/api/action/package_search'

params = {'q': '*:*', 'rows': 10}

r_openBCN = requests.get(url_bcn, params=params)

if r_openBCN.status_code == 200:
    resultados = r_openBCN.json()['result']['results']
    for ds in resultados:
        print(f"Título: {ds['title']} | ID: {ds['name']}")

Título: Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council | ID: rebuts-quota-padro-residus-bcn
Título: Receipts and quota of the register of the Vados Tax of the Barcelona City Council | ID: rebuts-quota-padro-guals
Título: Receipts and charges from the motor vehicle tax roll of the Barcelona City Council | ID: rebuts-quota-padro-vehicle-bcn
Título: Immigrants | ID: pad_imm_mdbas
Título: Emigrants | ID: pad_emi_mdbas
Título: Cancellations for undue inscription | ID: pad_bai_mdbas
Título: Registrations by omission | ID: pad_alt_mdbas
Título: Deaths | ID: pad_def_mdbas
Título: Births | ID: pad_nai_mdbas
Título: Population by geographical region of nationality and sex | ID: pad_mdb_nacionalitat-regio_sexe

Hacemos una búsqueda más concreta, por ejemplo los nombres más populares.

In [206]:
params = {'q': 'Most popular names', 'rows': 10}

r_openBCN = requests.get(url_bcn, params=params)

if r_openBCN.status_code == 200:
    results = r_openBCN.json()['result']['results']
    for ds in results:
        print(f"Título: {ds['title']} | {ds['id']} |  ID: {ds['name']}")

Título: Most popular names by sex and decade of birth | 769a7f14-3353-4b74-b35c-8abfc20e357c |  ID: pad_m_nom_decada_sexe

### **Ejercicio 2.**

####  De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON.

Eligimos el dataset con **ID pad_m_nom_decada_sexe** para mirar los nombres más populares del año 2025.

In [ ]:
id_dataset = 'pad_m_nom_decada_sexe'

### **Ejercicio 3.**

#### Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search para recuperar al menos 100 registros.

In [237]:
url = 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show'

params = {
    'id': id_dataset,
}

response = requests.get(url, params=params)
data = response.json()

resultados = data['result']['resources']

for res in resultados:
    print(res['id'], res['name'])

7446b652-c26a-4137-8f5a-f0fa432adb1d 2025_pad_m_nom_decada_sexe.csv
274a2e37-5986-4899-a86a-9f7441aac16a 2025_pad_m_nom_decada_sexe.json
5a9505b8-4baa-4b37-a38e-4d2a78df040e 2024_pad_m_nom_decada_sexe.csv
810d1d41-aaae-48db-8e23-93870bbebaa0 2024_pad_m_nom_decada_sexe.json
5434e6bf-64f3-4c49-b9f9-0d715b28ecc4 2023_pad_m_nom_decada_sexe.csv
b81617ef-7100-4f7d-b0b8-7059a17aed9b 2023_pad_m_nom_decada_sexe.json
b006ea5f-b822-4ce3-8cea-df6533cff364 2022_pad_m_nom_decada_sexe.csv
75a6c9ad-7c01-4f63-9020-17630a786645 2022_pad_m_nom_decada_sexe.json
7aaf61c6-69f7-4246-8086-39a1fabb7fc8 2021_pad_m_nom_decada_sexe.csv
558b56bc-6192-4687-9531-db1bdcc67a95 2021_pad_m_nom_decada_sexe.json
d4bb5830-cd77-451d-89b6-ba96b36eab26 2020_pad_m_nom_decada_sexe.csv
9e8debd4-fc24-4603-acf2-d12c58c86eca 2020_pad_m_nom_decada_sexe.json
7e182c65-4647-4b45-93dc-900f63ae4c74 2019_pad_m_nom_decada_sexe.csv
8cf16484-8e38-41dc-8dd0-f49ffb5c505d 2019_pad_m_nom_decada_sexe.json
a68eacd3-8195-463e-85b4-b486b0d222ac 2018_pad_m_nom_decada_sexe.csv
1d05379a-af54-4d72-b112-8ae88ef53591 2018_pad_m_nom_decada_sexe.json
9ae683b2-751d-41df-b07f-86bc2b084469 2017_pad_m_nom_decada_sexe.csv
d096859c-9658-451c-a1a1-c16376f48a32 2017_pad_m_nom_decada_sexe.json
99a0c564-3f23-4357-9e3b-ca8fe6f81f9d 2016_pad_m_nom_decada_sexe.csv
bb04652f-7991-4bb9-aa3b-617c963583d3 2016_pad_m_nom_decada_sexe.json
aa5be5c0-50fd-48dc-97cf-8de92c82e532 2015_pad_m_nom_decada_sexe.csv
9b4a5226-e8e6-4092-b977-b47931f45da9 2015_pad_m_nom_decada_sexe.json
863d6b11-0e9b-4515-91e4-cf5742fecb51 2014_pad_m_nom_decada_sexe.csv
e1d99d5d-fd03-4d90-9e58-703f43df9ea4 2014_pad_m_nom_decada_sexe.json
9ed13eb3-d3af-4f56-a307-9e169fbb2740 2013_pad_m_nom_decada_sexe.csv
df519742-3304-4d4d-914f-2dae5a9f879b 2013_pad_m_nom_decada_sexe.json
e3967a40-ff8f-4d4a-b0da-6c78d5f5d186 2012_pad_m_nom_decada_sexe.csv
843bbc08-da0f-4c9c-bfcb-7e68b71f5a7b 2012_pad_m_nom_decada_sexe.json
b7c39e4a-6afd-442e-bb56-507fcab75222 2011_pad_m_nom_decada_sexe.csv
a26a4a59-180d-4a01-a235-cea6341078a6 2011_pad_m_nom_decada_sexe.json
be1c2331-056b-43f3-844e-c6da71831205 2010_pad_m_nom_decada_sexe.csv
6b3d140d-a632-475d-ba52-f065ed902334 2010_pad_m_nom_decada_sexe.json
eabc4ae1-8801-4927-80c4-b287fae315fb 2009_pad_m_nom_decada_sexe.csv
7d9a60bc-c8ee-4c95-b76e-3435aceaaf04 2009_pad_m_nom_decada_sexe.json
5a3eb64c-a803-4390-a99d-62ad79dc3b89 2008_pad_m_nom_decada_sexe.csv
a5838eb6-630e-460d-b0e9-e64bcefc26f7 2008_pad_m_nom_decada_sexe.json
97a0625c-4bf5-4ed6-9721-444ca754a0a3 2007_pad_m_nom_decada_sexe.csv
6b12ebbc-76dd-43e9-9051-bc3b18b6d0be 2007_pad_m_nom_decada_sexe.json
6a4f3ae9-ba00-4a27-be8a-c6c62540cbc7 2006_pad_m_nom_decada_sexe.csv
63107c69-bd62-4ac1-afd2-8b52b0f35c62 2006_pad_m_nom_decada_sexe.json
41dee2e6-12fd-46fd-9625-b45f7b2c8640 2005_pad_m_nom_decada_sexe.csv
1e18b4ec-f611-4b9a-b3d9-b8158f6cf620 2005_pad_m_nom_decada_sexe.json
ce77ada3-843f-4650-8a75-eedd9ac8e3fb 2004_pad_m_nom_decada_sexe.csv
9a2bac00-5fa6-401f-b899-ff67f1326787 2004_pad_m_nom_decada_sexe.json
01909757-79f0-4bef-b22e-5cacb210b0cd 2003_pad_m_nom_decada_sexe.csv
bebb6d10-b111-4ade-8029-1d1c0637aabe 2003_pad_m_nom_decada_sexe.json
27ccb29c-0314-4eb1-a4a8-7eab5c5f0a6d 2002_pad_m_nom_decada_sexe.csv
ee6a0f9b-2227-4911-88c3-a1e16dba0c20 2002_pad_m_nom_decada_sexe.json
1a76cce8-fffb-4daa-beff-af265b2b9f5c 2001_pad_m_nom_decada_sexe.csv
4d79e1ca-bd73-4d64-a225-a7c8578f261a 2001_pad_m_nom_decada_sexe.json
39a7fef5-f125-4961-800f-d309c58b1ac6 2000_pad_m_nom_decada_sexe.csv
de3cb4d4-91ee-4134-8e99-5b21c2462849 2000_pad_m_nom_decada_sexe.json
a88df607-b52c-4626-98e7-0be15638f518 1999_pad_m_nom_decada_sexe.csv
7e7efd07-615f-4e44-8771-39a5805b57e3 1999_pad_m_nom_decada_sexe.json
42659624-ee77-4cd9-92f6-80d27c5f20eb 1998_pad_m_nom_decada_sexe.csv
88872758-f381-4c8c-ad7b-c7a9b8ef3e3a 1998_pad_m_nom_decada_sexe.json
ab9a7eba-cc68-4823-83ce-e7aa4f5c51bc 1997_pad_m_nom_decada_sexe.csv
93a784c1-74f7-416e-bd55-41c93ccf575b 1997_pad_m_nom_decada_sexe.json

### **Ejercicio 3.**

#### Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search para recuperar al menos 100 registros.

Eligimos el primero recurso con id 7446b652-c26a-4137-8f5a-f0fa432adb1d

In [240]:
url_recurso =' https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=7446b652-c26a-4137-8f5a-f0fa432adb1d'

r_recurso = requests.get(url_recurso)

In [247]:
r_recurso.json()['result']['records']

[{'NOM': 'MONTSERRAT',
  'SEXE': '1',
  'Valor': '3976',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 1},
 {'NOM': 'DAVID',
  'SEXE': '2',
  'Valor': '3922',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 2},
 {'NOM': 'MONTSERRAT',
  'SEXE': '1',
  'Valor': '3515',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 3},
 {'NOM': 'JOSE',
  'SEXE': '2',
  'Valor': '3169',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 4},
 {'NOM': 'JORDI',
  'SEXE': '2',
  'Valor': '3130',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 5},
 {'NOM': 'MARTA',
  'SEXE': '1',
  'Valor': '3062',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 6},
 {'NOM': 'ANTONIO',
  'SEXE': '2',
  'Valor': '3047',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 7},
 {'NOM': 'ANTONIO',
  'SEXE': '2',
  'Valor': '2904',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 8},
 {'NOM': 'JOSE',
  'SEXE': '2',
  'Valor': '2861',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 9},
 {'NOM': 'M CARMEN',
  'SEXE': '1',
  'Valor': '2693',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 10},
 {'NOM': 'JORDI',
  'SEXE': '2',
  'Valor': '2676',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 11},
 {'NOM': 'ANTONIO',
  'SEXE': '2',
  'Valor': '2635',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 12},
 {'NOM': 'CARMEN',
  'SEXE': '1',
  'Valor': '2619',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 13},
 {'NOM': 'LAURA',
  'SEXE': '1',
  'Valor': '2595',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 14},
 {'NOM': 'CRISTINA',
  'SEXE': '1',
  'Valor': '2534',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 15},
 {'NOM': 'DAVID',
  'SEXE': '2',
  'Valor': '2514',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 16},
 {'NOM': 'MARC',
  'SEXE': '2',
  'Valor': '2485',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 17},
 {'NOM': 'LAURA',
  'SEXE': '1',
  'Valor': '2447',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 18},
 {'NOM': 'MARIA',
  'SEXE': '1',
  'Valor': '2437',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 19},
 {'NOM': 'MARTA',
  'SEXE': '1',
  'Valor': '2408',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 20},
 {'NOM': 'NURIA',
  'SEXE': '1',
  'Valor': '2360',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 21},
 {'NOM': 'MONICA',
  'SEXE': '1',
  'Valor': '2357',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 22},
 {'NOM': 'MANUEL',
  'SEXE': '2',
  'Valor': '2334',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 23},
 {'NOM': 'M CARMEN',
  'SEXE': '1',
  'Valor': '2286',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 24},
 {'NOM': 'MARIA',
  'SEXE': '1',
  'Valor': '2282',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 25},
 {'NOM': 'DANIEL',
  'SEXE': '2',
  'Valor': '2281',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 26},
 {'NOM': 'FRANCISCO',
  'SEXE': '2',
  'Valor': '2280',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 27},
 {'NOM': 'MARC',
  'SEXE': '2',
  'Valor': '2248',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 28},
 {'NOM': 'MONTSERRAT',
  'SEXE': '1',
  'Valor': '2242',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 29},
 {'NOM': 'MARIA',
  'SEXE': '1',
  'Valor': '2178',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '2',
  '_id': 30},
 {'NOM': 'MANUEL',
  'SEXE': '2',
  'Valor': '2161',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 31},
 {'NOM': 'FRANCISCO',
  'SEXE': '2',
  'Valor': '2160',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 32},
 {'NOM': 'DANIEL',
  'SEXE': '2',
  'Valor': '2139',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 33},
 {'NOM': 'JORGE',
  'SEXE': '2',
  'Valor': '2095',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 34},
 {'NOM': 'CARLOS',
  'SEXE': '2',
  'Valor': '2088',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 35},
 {'NOM': 'CARMEN',
  'SEXE': '1',
  'Valor': '2069',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 36},
 {'NOM': 'JAVIER',
  'SEXE': '2',
  'Valor': '2069',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 37},
 {'NOM': 'MARTA',
  'SEXE': '1',
  'Valor': '2064',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 38},
 {'NOM': 'CARLOS',
  'SEXE': '2',
  'Valor': '2060',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 39},
 {'NOM': 'CRISTINA',
  'SEXE': '1',
  'Valor': '2056',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 40},
 {'NOM': 'M CARMEN',
  'SEXE': '1',
  'Valor': '2009',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 41},
 {'NOM': 'OSCAR',
  'SEXE': '2',
  'Valor': '1988',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 42},
 {'NOM': 'JUAN',
  'SEXE': '2',
  'Valor': '1973',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 43},
 {'NOM': 'SILVIA',
  'SEXE': '1',
  'Valor': '1969',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 44},
 {'NOM': 'MARTA',
  'SEXE': '1',
  'Valor': '1957',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 45},
 {'NOM': 'MARIA',
  'SEXE': '1',
  'Valor': '1934',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 46},
 {'NOM': 'MANUEL',
  'SEXE': '2',
  'Valor': '1930',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 47},
 {'NOM': 'JUAN',
  'SEXE': '2',
  'Valor': '1915',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 48},
 {'NOM': 'MONTSERRAT',
  'SEXE': '1',
  'Valor': '1913',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 49},
 {'NOM': 'LAURA',
  'SEXE': '1',
  'Valor': '1900',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 50},
 {'NOM': 'JOSE',
  'SEXE': '2',
  'Valor': '1899',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 51},
 {'NOM': 'CARMEN',
  'SEXE': '1',
  'Valor': '1896',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '2',
  '_id': 52},
 {'NOM': 'JORDI',
  'SEXE': '2',
  'Valor': '1895',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 53},
 {'NOM': 'ANNA',
  'SEXE': '1',
  'Valor': '1893',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 54},
 {'NOM': 'DAVID',
  'SEXE': '2',
  'Valor': '1873',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 55},
 {'NOM': 'NURIA',
  'SEXE': '1',
  'Valor': '1873',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 56},
 {'NOM': 'FRANCISCO',
  'SEXE': '2',
  'Valor': '1863',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 57},
 {'NOM': 'SONIA',
  'SEXE': '1',
  'Valor': '1858',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 58},
 {'NOM': 'SERGIO',
  'SEXE': '2',
  'Valor': '1818',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 59},
 {'NOM': 'JOSEFA',
  'SEXE': '1',
  'Valor': '1814',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 60},
 {'NOM': 'SANDRA',
  'SEXE': '1',
  'Valor': '1790',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 61},
 {'NOM': 'DANIEL',
  'SEXE': '2',
  'Valor': '1782',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 62},
 {'NOM': 'EVA',
  'SEXE': '1',
  'Valor': '1749',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 63},
 {'NOM': 'ANNA',
  'SEXE': '1',
  'Valor': '1742',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 64},
 {'NOM': 'JORGE',
  'SEXE': '2',
  'Valor': '1737',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 65},
 {'NOM': 'MARC',
  'SEXE': '2',
  'Valor': '1732',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 66},
 {'NOM': 'M TERESA',
  'SEXE': '1',
  'Valor': '1730',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 67},
 {'NOM': 'CRISTINA',
  'SEXE': '1',
  'Valor': '1729',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 68},
 {'NOM': 'ISABEL',
  'SEXE': '1',
  'Valor': '1683',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 69},
 {'NOM': 'ANTONIO',
  'SEXE': '2',
  'Valor': '1651',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 70},
 {'NOM': 'JAVIER',
  'SEXE': '2',
  'Valor': '1649',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 71},
 {'NOM': 'M TERESA',
  'SEXE': '1',
  'Valor': '1633',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 72},
 {'NOM': 'ANDREA',
  'SEXE': '1',
  'Valor': '1627',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 73},
 {'NOM': 'JAVIER',
  'SEXE': '2',
  'Valor': '1607',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 74},
 {'NOM': 'ALEX',
  'SEXE': '2',
  'Valor': '1597',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 75},
 {'NOM': 'MARIA',
  'SEXE': '1',
  'Valor': '1575',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 76},
 {'NOM': 'ANA MARIA',
  'SEXE': '1',
  'Valor': '1571',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 77},
 {'NOM': 'PILAR',
  'SEXE': '1',
  'Valor': '1542',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 78},
 {'NOM': 'SILVIA',
  'SEXE': '1',
  'Valor': '1541',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 79},
 {'NOM': 'MARIA',
  'SEXE': '1',
  'Valor': '1538',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 80},
 {'NOM': 'PAULA',
  'SEXE': '1',
  'Valor': '1534',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 81},
 {'NOM': 'SUSANA',
  'SEXE': '1',
  'Valor': '1534',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 82},
 {'NOM': 'MARC',
  'SEXE': '2',
  'Valor': '1528',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '10',
  '_id': 83},
 {'NOM': 'ISABEL',
  'SEXE': '1',
  'Valor': '1527',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '3',
  '_id': 84},
 {'NOM': 'CARLOS',
  'SEXE': '2',
  'Valor': '1520',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 85},
 {'NOM': 'POL',
  'SEXE': '2',
  'Valor': '1501',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 86},
 {'NOM': 'JORDI',
  'SEXE': '2',
  'Valor': '1487',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 87},
 {'NOM': 'JOSE',
  'SEXE': '2',
  'Valor': '1481',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '2',
  '_id': 88},
 {'NOM': 'PAU',
  'SEXE': '2',
  'Valor': '1466',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 89},
 {'NOM': 'ALEJANDRO',
  'SEXE': '2',
  'Valor': '1453',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 90},
 {'NOM': 'LAIA',
  'SEXE': '1',
  'Valor': '1451',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 91},
 {'NOM': 'JULIA',
  'SEXE': '1',
  'Valor': '1420',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '9',
  '_id': 92},
 {'NOM': 'ISABEL',
  'SEXE': '1',
  'Valor': '1417',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 93},
 {'NOM': 'CRISTINA',
  'SEXE': '1',
  'Valor': '1410',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 94},
 {'NOM': 'JUAN',
  'SEXE': '2',
  'Valor': '1396',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 95},
 {'NOM': 'YOLANDA',
  'SEXE': '1',
  'Valor': '1388',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '6',
  '_id': 96},
 {'NOM': 'PAULA',
  'SEXE': '1',
  'Valor': '1385',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '8',
  '_id': 97},
 {'NOM': 'FRANCISCO JAVIER',
  'SEXE': '2',
  'Valor': '1366',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '5',
  '_id': 98},
 {'NOM': 'ALBERT',
  'SEXE': '2',
  'Valor': '1364',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '7',
  '_id': 99},
 {'NOM': 'MERCEDES',
  'SEXE': '1',
  'Valor': '1357',
  'Data_Referencia': '2025-01-01T00:00:00',
  'DECADA': '4',
  '_id': 100}]

### **Ejercicio 4.**

#### Convierte los resultados a un DataFrame.

In [252]:
df_nombres_2025= pd.DataFrame(r_recurso.json()['result']['records'])
df_nombres_2025.head(10)

          NOM SEXE Valor      Data_Referencia DECADA  _id
0  MONTSERRAT    1  3976  2025-01-01T00:00:00      5    1
1       DAVID    2  3922  2025-01-01T00:00:00      6    2
2  MONTSERRAT    1  3515  2025-01-01T00:00:00      4    3
3        JOSE    2  3169  2025-01-01T00:00:00      3    4
4       JORDI    2  3130  2025-01-01T00:00:00      6    5
5       MARTA    1  3062  2025-01-01T00:00:00      6    6
6     ANTONIO    2  3047  2025-01-01T00:00:00      4    7
7     ANTONIO    2  2904  2025-01-01T00:00:00      3    8
8        JOSE    2  2861  2025-01-01T00:00:00      4    9
9    M CARMEN    1  2693  2025-01-01T00:00:00      4   10

### **Ejercicio 5.**

#### Guarda DataFrame en un archivo .csv.

In [258]:
df_nombres_2025.to_csv('Nombres populares en el año 2025.csv')