In [46]:
import pandas as pd

In [47]:
df_age_equipment = pd.read_csv('../Dataset/age_equipment.csv')
df_mechanic = pd.read_csv('../Dataset/mechanic.csv')

## Revisión de datos y resolución de problemas de tipificación

#### Dataframe **df_age_equipment** con datos de antigüedad de maquinas de costura.

In [48]:
print('Número de registros en archivo age_equipment.csv: ', df_age_equipment.shape[0])

if 'Unnamed: 0' in df_age_equipment.columns:
    df_age_equipment.drop(columns='Unnamed: 0', inplace=True)
df_age_equipment.head(5)

Número de registros en archivo age_equipment.csv:  7890

   Equipment   Age
0  1014059.0  22.0
1  1156767.0  19.0
2  1011680.0  22.0
3  1023346.0  21.0
4  1020406.0  23.0

#### Revisión de valores nulos.

In [49]:
df_age_equipment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7890 entries, 0 to 7889
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Equipment  6963 non-null   float64
 1   Age        6963 non-null   float64
dtypes: float64(2)
memory usage: 123.4 KB

In [50]:
# Valores nulos por variable
nulos_age_equip = df_age_equipment.isnull().sum()

# Calcular el porcentaje de nulos
nulos_age_equip_pers = (nulos_age_equip / len(df_age_equipment)) * 100

null_info_age_equip = pd.DataFrame({
    'Variable': nulos_age_equip.index,
    'Nulos': nulos_age_equip.values,
    'Porcentaje de Nulos': nulos_age_equip_pers.values
})

null_info_age_equip

    Variable  Nulos  Porcentaje de Nulos
0  Equipment    927            11.749049
1        Age    927            11.749049

In [51]:
df_age_equipment[df_age_equipment['Age'].isnull()].head(10)

      Equipment  Age
6963        NaN  NaN
6964        NaN  NaN
6965        NaN  NaN
6966        NaN  NaN
6967        NaN  NaN
6968        NaN  NaN
6969        NaN  NaN
6970        NaN  NaN
6971        NaN  NaN
6972        NaN  NaN

Eliminamos las filas con nulos.

In [52]:
df_age_equipment.dropna(axis=0, inplace=True)

In [53]:
df_age_equipment.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6963 entries, 0 to 6962
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Equipment  6963 non-null   float64
 1   Age        6963 non-null   float64
dtypes: float64(2)
memory usage: 163.2 KB

Cambiamos el tipo de ambas columas por int.

In [54]:
df_age_equipment['Age'] = df_age_equipment['Age'].astype(int)
df_age_equipment['Equipment'] = df_age_equipment['Equipment'].astype('int')

Cambiamos primeras letras de los nombres de columnas por minúsculas.

In [55]:
df_age_equipment.columns = df_age_equipment.columns.str.lower()

In [56]:
df_age_equipment.head(5)

   equipment  age
0    1014059   22
1    1156767   19
2    1011680   22
3    1023346   21
4    1020406   23

#### **Número de maquinas** con información de **antigúedad.**

In [57]:
print('Número de maquinas con información de antigúedad:', df_age_equipment.shape[0])

Número de maquinas con información de antigúedad: 6963

#### Dataframe **df_mechanic** con nombres de mecánicos y sus experiencia laboral en la fabrica.

In [58]:
if 'Unnamed: 0' in df_mechanic.columns:
    df_mechanic.drop(columns='Unnamed: 0', inplace=True)

df_mechanic.sort_values(by='mechanic').head(10)

                                mechanic  antiquity
15                          ALLAN RIVERA         18
7                        ANGEL MATAMOROS         18
114          Abel Alberto Ramirez Rivera         10
160             Abidail Alexander Garcia          1
87   Adalberto Jeremias Rodriguez Zometa          5
95       Albano Siloe Castillo Canizales          8
222           Alex Antonio Escobar Navas          3
98                       Alfonso Escobar          9
218                         Ander Castro          3
102                            Angel Mex         10

In [59]:
df_mechanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   mechanic   227 non-null    object
 1   antiquity  227 non-null    int64
dtypes: int64(1), object(1)
memory usage: 3.7+ KB

#### Revisión de valores nulos.

In [60]:
# Valores nulos por variable
nulos_mechanic = df_mechanic.isnull().sum()

# Calcular el porcentaje de nulos
nulos_mechanic = (nulos_mechanic / len(df_mechanic)) * 100

null_info_mechanic = pd.DataFrame({
    'Variable': nulos_mechanic.index,
    'Nulos': nulos_mechanic.values,
    'Porcentaje de Nulos': nulos_mechanic.values
})

null_info_mechanic

    Variable  Nulos  Porcentaje de Nulos
0   mechanic    0.0                  0.0
1  antiquity    0.0                  0.0

#### Cambiamos el tipo de variable **mechanic** por category

In [61]:
df_mechanic['mechanic'] = df_mechanic['mechanic'].astype('category')

#### **Número de mecánocos** con información de **experiencia.**

In [62]:
print('Número de mecánicos con información de experiencia:', df_mechanic.shape[0])

Número de mecánicos con información de experiencia: 227

#### Guardamos datasets limpiados

In [63]:
df_age_equipment.to_parquet('../Dataset limpiado/age_equipment_limp.parquet')
df_mechanic.to_parquet('../Dataset limpiado/mechanic_limp.parquet')